### ISSUE TITLE
Better preview metadata

### ISSUE THREAD

**Issue by leethax666** [cloudrac3r/cadencegq#1]
Links when previewed in other apps such as Discord or Riot should have better previews conforming to http://ogp.me/ such as 

    og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
    og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
    og:image - An image URL which should represent your object within the graph.
    og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".

**Comment by cloudrac3r** [comment]
Could you give an example of how data could be previewed?

**Comment by leethax666** [comment]
Here's an example of youtube vs cloudtube in Riot. Using the metadata tags from the above website will allow richer embeds and previews for users

![image](https://user-images.githubusercontent.com/1305475/43042176-30b8aa92-8d2b-11e8-889e-7305296da7f5.png)

**Comment by cloudrac3r** [comment]
Unfortunately it's not that easy. When the page loads nothing is immediately known about the video. The page loads, then JavaScript is run which sends a request to the API which eventually returns video data. The loading indicator is then hidden and information is filled into the appropriate areas on the page. This means I can't include information about the video in the meta tags.

An alternative would be to make the server prefill all the information as the page is loaded, which can be done, but will be a little annoying.

**Comment by cloudrac3r** [comment]
The rewrite branch is now merged into master, which should in theory make the metadata look nice (among other things). I'll do some final testing now and if all is well probably deploy this to the server tomorrow and see how it looks.

**Comment by cloudrac3r** [comment]
The rewrite is published and opengraph tags do appear to render correctly in Riot (https://cadence.gq/api/images/89cd18) and Discord. This issue appears to now be fixed, so I'll close it. Feel free to reopen if you have any other suggestions related to these tags!

**Comment by leethax666** [comment]
Wonderful! Thank you

On August 12, 2018 9:10:32 PM PDT, Edward Fish <notifications@github.com> wrote:
>The rewrite is published and opengraph tags do appear to render
>correctly in Riot (https://cadence.gq/api/images/89cd18) and Discord.
>This issue appears to now be fixed, so I'll close it. Feel free to
>reopen if you have any other suggestions related to these tags!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cloudrac3r/cadencegq/issues/1#issuecomment-412403941

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
