### ISSUE TITLE
Error on create new Pastes

### ISSUE THREAD

**Issue by marcussacana** [cloudrac3r/cadencegq#10]
![image](https://user-images.githubusercontent.com/10576957/76821374-87697680-67ec-11ea-92ee-06a9e2ddfe55.png)

Looks like works if I edit a existing one.

**Comment by cloudrac3r** [comment]
Thank you for the report! Fixed in cb625cf7499a9683f75fc6738c914f4d06f503b3. You should be able to create pastes again.
