### ISSUE TITLE
Add multilanguage

### ISSUE THREAD

**Issue by wuniversales** [cloudrac3r/cadencegq#12]
I can translate into Spanish, but I need the strings.

**Comment by cloudrac3r** [comment]
Sorry, I won't implement other languages. This website has just been in keep-it-running mode for a while now. I do not wish to create new features. The code is quite old and bad and I do not enjoy working on it. I prefer to dedicate my time to other projects, like Bibliogram.

Thank you for your offer to provide translations, though. If you want, you can always fork the site, edit the files, and then host that fork yourself. The files to edit should be found in the "pug" folder.
