### ISSUE TITLE
[Request] Filter Paste Enumeration

### ISSUE THREAD

**Issue by marcussacana** [cloudrac3r/cadencegq#14]
If possible, you can add an optional paramter to the `GET /api/pastes` to filter the pastes by author?

Also, I didn't tested yet, but your API allow cross-domain?

**Comment by cloudrac3r** [comment]
The API itself does not care about domain, but your browser might. I'm not sure what the CORS headers are set to.

I can add that. Would you like to filter by user ID, or username, or...?

— Cadence

**Comment by marcussacana** [comment]
I think by author, the username it's a better choice.

**Comment by cloudrac3r** [comment]
Done. Use the query parameter `author`, for example, `cadence.moe/api/pastes?preview=5&author=benis`.

**Comment by marcussacana** [comment]
Thank you!
