### ISSUE TITLE
About the Api

### ISSUE THREAD

**Issue by marcussacana** [cloudrac3r/cadencegq#15]
Hi, me again, this time isn't really a bug, maybe you can think as a request...?
Anyway, I'm trying use your API from a github pages site,
In the gh-pages settings, we can do cross-domain request but only with `GET/POST` methods
![image](https://user-images.githubusercontent.com/10576957/82617841-a8ad6100-9ba7-11ea-82d8-0e55624eccd0.png)
![image](https://user-images.githubusercontent.com/10576957/82617928-f6c26480-9ba7-11ea-8299-ee23b5f9b016.png)
As you can see, this is enougth to create and read pastes in your API, but unfortally to edit we must use the `PATCH` method.

Anyway, This is not much of a request because I have a way of getting around it,  
I have my own hosted php server, Then I can use a small php script as proxy to do `PATCH` request using the `POST` from the user machine.

Currently I quite like how your API was made, it is simple, practical and with clear usage, I have nothing to complain about, So I even thought twice before I came to ask for this.

Anyway my "Proposal" is to implment an alternative way to edit the paste using only simple http methods (`GET/POST`);

If you ask me how I think is cool, i can think in 2 ways, they are
- Create `POST /api/pastes/{pasteID}/edit` api 
(I don't think this one is so interesting because it would make a 'duplicate' API)
- Create a optional parameter at `POST /api/pastes`  like `pasteID`
(I think this option is better, when the optional paramter is set the paste is edited)

In my opinion, this will interfere a little in the beautiful organization you made with your API, so you don't have to think about it too much, because I have an alternative to work around the problem, I just came here to ask why it would be more practical if I didn't need to depend on a 'proxy' to use the API, even for privacy reasons.

Also, I have a doubt about the api
![image](https://user-images.githubusercontent.com/10576957/82618954-e069d800-9baa-11ea-8acf-7e88e66c357b.png)
Here says we must verify the account with you before upload, no problem,
but what you mean by 'upload'? because create a paste isn't very a 'upload' i'm with doubt if the pastes is affected by this policy too.

**Comment by cloudrac3r** [comment]
Thanks for the long message!

I believe I can just fix cross-origin PATCH requests.

Pastes are considered uploads. However, your account is old enough that it is not affected. If you have more accounts that you would like to enable uploads on, please let me know.

**Comment by marcussacana** [comment]
I see, well... nothing now, but in the future I will give instructions to my users active the account.
anyway, to you is better ask for activation in the github or email?

**Comment by cloudrac3r** [comment]
Actually I could make it possible for you (or anyone with an account) to approve other accounts for upload. What do you think of that?

**Comment by marcussacana** [comment]
This looks cool, but do you think will be safe to you?

**Comment by cloudrac3r** [comment]
We'll find out. I can undo it.

**Comment by marcussacana** [comment]
haha, no problem then.
My program will be used by the members of my translation group, and we have like 30 members, isn't all active, but the active members will must create a account in the cadence, I'm planning use the paste api as an online backup of the translation progress;
Any problem to you?
This time we don't will create many pastes but will keep they for a good time

**Comment by cloudrac3r** [comment]
That's perfectly fine.

**Comment by cloudrac3r** [comment]
I added access control which means that cross-origin `PATCH /api/pastes/{pasteID}` _should_ be allowed. I also created `POST /api/pastes/{pasteID}/edit` to allow you to send POST requests to edit. Let me know if there are problems with either of these.

I also changed the encoding of data from `/raw` to be UTF-8 to make sure Japanese characters render correctly in the browser.

**Comment by marcussacana** [comment]
@cloudrac3r working like a charm, thank you.
By the way, the paste have any length limit?
Just to ensure...

**Comment by cloudrac3r** [comment]
nginx imposes a 20 MB upload limit. the site has no size limits itself.

of course, remember that lots of content in one paste (more that 500,000 bytes or so) will be slow for you to upload, download, and render on screen every time.

**Comment by marcussacana** [comment]
Yeah, no problem, I don't think a paste will have more than 1mb

**Comment by cloudrac3r** [comment]
Just thought I'd note: Seems like the domain `cadence.gq` was cancelled recently. This used to be another domain for the same website, but now it's gone. Make sure you use `cadence.moe` to access the website.

**Comment by marcussacana** [comment]
haha thank you, but in the true I even didn't know about the cadence.gq domain, my code is already using the cadence.moe
