### ISSUE TITLE
2160p by default

### ISSUE THREAD

**Issue by fabi-hub** [cloudrac3r/cadencegq#17]
Hello,

is it possible to set 2160p as default resolution?

Thanks

**Comment by cloudrac3r** [comment]
I'm not sure. It might be easy, it might be hard.

HQ playback (the formats with the ! indicator) are still somewhat buggy in playback, so I don't want to make them the default. I'd have to add an option for it at least.

**Comment by cloudrac3r** [comment]
This is an available feature on https://tube.cadence.moe .
