### ISSUE TITLE
Livestreams?

### ISSUE THREAD

**Issue by Yoposoc** [cloudrac3r/cadencegq#18]
Trying to find a invidious clone. I like how slick your site looks!

Can livestreams work? For me, they totally break and show me nothing.

**Comment by cloudrac3r** [comment]
Thanks. While it would be nice if I had livestreams, I have no idea how to make them work.

You should try FreeTube. Look up the name to find the website, or join the discussion on Matrix: https://matrix.to/#/#freetube:matrix.org

**Comment by Yoposoc** [comment]
Very cool, it was a bit glitchy at first, but it works!
