### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by ShivenV** [cloudrac3r/cadencegq#19]
Complete newbie here trying to get the entire site setup. Please bear with me.

I got all the way until the part where you have to make main.db and auth.json. As someone who has no experience with anything like this, could you tell me how to do this, or recommend me a thing that I should learn? 

Thank you in advance,
Shiven

**Comment by cloudrac3r** [comment]
Wow, you're the first person to actually ever try to run this.

Those instructions are out of date. I can write up new instructions, but you'll have to wait about a week, because I am extremely stressed IRL currently.

The site is also pending some major work to break its dependence with invidio.us, which will soon be closing. So you might want to wait and come back to this a bit later, if you're still interested.

Which specific parts of the site are you interested in using? I assume CloudTube?

**Comment by PowerMan2206** [comment]
@cloudrac3r I'm here 'cause I want the same thing as the guy above. Don't wanna leech off this post but I might as well ask some questions while I'm here:
- Is it possible to just host CloudTube, without the other stuff?
- What's up with no thumbnails?
- I thought this was supposed to use the Invidious API, why do you still need a *YouTube* API key?
- It's been over a week :P 

And uhh yeah that's all

**Comment by cloudrac3r** [comment]
I'm currently working on a rewrite of CloudTube. This rewrite will make it be only CloudTube, separate from the rest of my site. I will write a post on cadence.moe/blog when I have more info.

Rewrite source is here https://git.sr.ht/~cadence/cloudtube and you must also run Second on the same machine https://git.sr.ht/~cadence/Second

**Comment by PowerMan2206** [comment]
Thanks for that but uhh... *How do I use it?*

**Comment by cloudrac3r** [comment]
I will write a post on cadence.moe/blog when I have more info.

**Comment by PowerMan2206** [comment]
Ah, ok then, My bad :/

**Comment by 6d6f6d6f** [comment]
Will you host instances in the future for this? Could they be accessible to Tor users? I appreciate all the work you've been doing for this kind of thing.

**Comment by cloudrac3r** [comment]
Yes, once the rewrite is done I will host an instance for the public. 
Current CloudTube links will probably redirect there. The person running 
each instance may decide whether access via Tor is permitted.

YouTube rate limits requests, to something in the range of 1000/day, and 
then requires a captcha. This means people who spam are doing damage by 
burning the server's limit. Tor is a very easy way for spammers to avoid 
IP blocks.

**Comment by ShivenV** [comment]
Thank you so much for all the work you are doing. I understand that maintaining an open source repository is a difficult job, and I hope you are not too stressed by it. Keep up the good work!

**Comment by cloudrac3r** [comment]
Hey, apparently I never gave an update on this issue. And it's been, uh, almost 18 months. Oops.

Well, you can check out https://tube.cadence.moe and https://sr.ht/~cadence/tube for a CloudTube instance and source repository.

It should be accessible to Tor users at the moment unless I messed something up. If you have anything else to comment, please use the new mailing list: https://lists.sr.ht/~cadence/tube-devel

Thanks for your continued interest!
