### ISSUE TITLE
Question and Feature Request

### ISSUE THREAD

**Issue by marcussacana** [cloudrac3r/cadencegq#3]
Well, My question is, how many requests you allow?
I want use the paste tool in a small 'low-end' bot to store pastes for a time, so what you think it's 'acceptable' to my bot do?

About the feature request, you can add a 'delete code' of a created paste?
I just need store the paste for, what? 5 seconds? And since I will create many pastes, I think it's better delete it...

--Edit
Seems we can delete it using the edit api, so... forget about this my feature request.

**Comment by cloudrac3r** [comment]
There's no internal limit on requests. I feel like 1 per second would be a sensible limit, though I can handle many more.

You can delete a paste by editing it to have no content.

Would you mind telling me why you need to store a few hundred pastes for 5 seconds each, by the way? That sounds rather... interesting.

**Comment by marcussacana** [comment]
Basically I have an service that I need 'upload' many text's, but the api of this service just allow catch the text from another url, basically you send an url and he receive the text in the content of this url, Currently to use this service with the content I want, I have to open an http server by myself and give the link from that server... 
But to open a server isn't nothing easy to non-developers, So I thought, "Why don't use this paste api to store the text instead create a server?"
Well, It's only me and a friend that will use this small bot, so I don't think will be a problem with this limit, thank you!
