### ISSUE TITLE
cloudtube: interpret invidio.us URLs

### ISSUE THREAD

**Issue by mehlon** [cloudrac3r/cadencegq#8]
It would be nice if putting in a URL like https://invidio.us/watch?v=57c94il3Eng&autoplay=1&continue=1
would work in the search.

**Comment by cloudrac3r** [comment]
I will work on this soon. Until then, you can copy the video ID, which is the part between `?v=` and `&`, and paste that into the search bar.

**Comment by cloudrac3r** [comment]
If this is still an issue for you, please raise it on the ticket tracker for new CloudTube. Either way, have a nice day! https://todo.sr.ht/~cadence/tube
